# First draft of config file.
# TODO: This is very user unfriendly.
# Make sure parameters are listed in a sensible
# order and fully explained with comments.
schemes:
    posterior:
        colour: 'RoyalBlue'
        symbol: '-'
        label: 'Posterior pdf'
        colour_map: 'GnBu'
        colours: ['RoyalBlue', 'SeaGreen']
        colour_bar_title: 'PDF'
        level_names: ['$2\sigma$ region', '$1\sigma$ region']
    posterior_mean:
        colour: 'SeaGreen'
        symbol: 'o'
        label: 'Posterior Mean'
    best_fit:
        colour: 'Brown'
        symbol: '*'
        label: 'Best-fit point'
        size: 12
    prof_like:
        colour: 'DarkOrange'
        symbol: '--'
        label: 'Profile likelihood'
        colour_map: 'Reds'
        colours: ['DarkOrange', 'Brown']
        colour_bar_title: 'PL'
        level_names: ['$2\sigma$ region', '$1\sigma$ region']
    prof_chi_sq:
        colour: 'DarkOrange'
        symbol: '--'
        label: '$\Delta \chi^2$'
        colours: ['Gold', 'Peru']
        level_names: ['$2\sigma$ excluded', '$1\sigma$ excluded']
    scatter:
        symbol: 'o'
        colour_map: 'Reds'
        size: 15
    conf_interval_s2:
        colour: 'DarkOrange'
        symbol: 'o'
        label: '$2\sigma$ confidence interval'
    conf_interval_s1:
        colour: 'Brown'
        symbol: 'o'
        label: '$1\sigma$ confidence interval'
    credible_region_s2:
        colour: 'SeaGreen'
        symbol: '-'
        label: '$2\sigma$ credible region'
    credible_region_s1:
        colour: 'RoyalBlue'
        symbol: '-'
        label: '$1\sigma$ credible region'
    tau_band:
        colour: 'RoyalBlue'
        label: 'Theory Error'
        
#########################################################################
plot_options:
    # Technical plot options.       
    dof: 10
    alpha: [0.05, 0.32] # Values of alpha, in ascending order.
    # AF This should be called alpha, and what breaks if not ascending?
    # plot_limits: [0,0.2,0,1.3]
    plot_limits: null 
    # bin_limits: [[0,1000],[0,1000]]
    bin_limits: null
    nbins: 70

    # Plot appearance.
    xticks: 5 # Numbers of ticks.
    yticks: 5
    
    plot_title: 'Fowlie (2014)'

    # Size in inches.
    #AF This may be redudant, it should be in the mpstyle sheet
    size: [8, 8]

    # For theoretical error on delta chi-squared plots.
    tau: 2
    
    #TODO this is now redundant - my apologies, I didn't
    # know about the mplstyle sheets before
    # Whether to use LaTeX.
    # - all: use LaTeX for math and text
    # - math: use LaTeX for math only
    # - none: do not use LaTeX at all
    use_tex: 'all'



















